#微服务配置
spring:
  application:
    name: content_service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.101.74.46:3306/xc_system?serverTimezone=UTC&userUnicode=true&useSSL=false&
    username: root
    password: 980606
# 日志文件配置路径
logging:
  config: classpath:log4j2-dev.xml